### PR TITLE
update bower version

### PR DESCRIPTION
**Pull request by csantero**
I got some errors running `bower install`. Updating bower fixed it.

### CODE REVIEW

**Comment by cyril-sf** [comment]
Thanks @csantero for the PR.

Can you give me a bit more details about the error you encountered?

**Comment by cyril-sf** [comment]
I had to update saucelabs to test the PR and ended up updating bower in that branch.

Thanks again.

**Comment by csantero** [comment]
@Cyril-sf I just went back to the previous commit and now I couldn't reproduce it, sadly. It happened during `bower install`, and I think it happened on a String.join. Sorry

**Comment by cyril-sf** [comment]
@csantero no problem

**Pull request closed without merging**
