### PR TITLE
Update the code for the tutorial

### PR DESCRIPTION
**Pull request by cyril-sf**
- Sync the tutorial with the latest Conductor/Oasis/RSVP.
- Add support for `allow-same-origin` on a sandboxed iframe (needed for the youtube card).
- Disable `autoupdate` on the `HeightService` (it doesn't work, it needs to be fixed)

### CODE REVIEW

**Comment by cyril-sf** [comment]
@hjdivad ready for review

**Comment by hjdivad** [comment]
@Cyril-sf https://saucelabs.com/tests/b93672a712ed454fbf7f5ee03fafa6d2

**Comment by cyril-sf** [comment]
@hjdivad good for review

**Comment by cyril-sf** [comment]
one thing I need to do after the review is to set the tags

**Pull request merged**
