### PR TITLE
HeightService uses the document's body to get the minimum dimensions

### LINKED ISSUE #21: Height service behavior is confusing when you have only inline elements as child nodes of body
My first attempt at a card was rendering the text "Hello, world". I was very confused because the height service measurements resulted in a zero width element (which I initially interpreted as not rendering at all).

Perhaps the height service could log an error in this case?

### PR DESCRIPTION
**Pull request by cyril-sf**
[Fixes #21]

### CODE REVIEW

**Comment by cyril-sf** [comment]
@hjdivad good for review

**Comment by hjdivad** [comment]
@Cyril-sf should have a test where children include some text nodes and some block elements. I don't think we want height + Σ childHeights.

**Comment by cyril-sf** [comment]
@hjdivad it takes the max between those values, not the sum, no?

**Comment by hjdivad** [comment]
@Cyril-sf what's the case where we need to compute both?

**Comment by wagenet** [comment]
Closing due to staleness.

**Pull request closed without merging**
