### PR TITLE
Add npm install step to tutorial setup

### PR DESCRIPTION
**Pull request by kagemusha**

### CODE REVIEW

**Comment by hjdivad** [comment]
@kagemusha good catch, thanks!

**Comment by kagemusha** [comment]
no prob!

**Comment by hjdivad** [comment]
@kagemusha and of course we'd love to hear any other feedback on the tutorial, API or anything else, either here or @hjdivad on twitter.

We (obviously?) want Conductor.js to be easy to learn and easy to use. ^_^

**Comment by kagemusha** [comment]
@hjdivad https://github.com/hjdivad will do!

On Mon, May 13, 2013 at 4:16 PM, David J. Hamilton <notifications@github.com

**Pull request merged**
