### PR TITLE
Rename promise fails to catch

### PR DESCRIPTION
**Pull request by seamus-oconnor**
Renamed promise .fails to .catch to silence Oasis deprecation warnings.

### CODE REVIEW

**Comment by lukemelia** [comment]
@hjdivad, would you mind restarting the Travis build for @seamus-oconner?

**Comment by hjdivad** [comment]
@lukemelia hey sorry for the late restart; I've done so now

**Comment by seamus-oconnor** [comment]
Travis failed again due to: "Could not create tunnel to Sauce Labs".

**Comment by cyril-sf** [comment]
I think that the problem is that our Saucelabs config does not work on PR submitted by not team members.

Let me double check that.

**Comment by wagenet** [comment]
Closing due to staleness.

**Pull request closed without merging**
