### PR TITLE
upgrade oasis

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by hjdivad** [comment]
@stefanpenner will do this in a bit; I think current oasis may have a problem in older FF; not totally sure, looking in to it.

**Comment by stefanpenner** [comment]
Sounds good, we needed to bump our dev version of conductor anyways to work with our inline adapter spike. So i figured we would share the upgrade. :)

**Comment by hjdivad** [comment]
upgraded oasis in 37701b9eae651d4a47688a3f67216cf2733a6f04

**Comment by stefanpenner** [comment]
<3

**Pull request closed without merging**
